### PR TITLE
LMW-245 AddBookmarkScreenlet sample for iOS

### PR DESCRIPTION
**Pull request by jmnavarro**

### CODE REVIEW

**Comment by ngaskill** [comment]
@jmnavarro @nhpatt There are 2 missing images in screenlet_creation.md. Otherwise, it looks good.

**Comment by jmnavarro** [comment]
@ngaskill those images are in other PR, so it will work as soon as we merge that one.

**Comment by ngaskill** [comment]
:+1:

**Comment by nhpatt** [comment]
:+1:

**Pull request merged**
