### PR TITLE
LMW-236 Documentation on how to create a Viewset

### PR DESCRIPTION
**Pull request by nhpatt**
Sorry for the delay in writing the documentation, do you think this solves all pending doubts/tasks regarding documentation?

### CODE REVIEW

**Comment by ngaskill** [comment]
@nhpatt No worries. There's just one area that needs more explanation: the Screenlet Packaging section in screenlet_creation.md. I put specific comments in the file. Also, the last two links in the section Packaging Your Views in view_creation.md are broken, and I couldn't find where they should go. Thanks.

**Comment by nhpatt** [comment]
I've added more instructions in how to create and package a screenlet in a different module.

Many links were broken because they need the new folder structure, I have replaced them with valid links and I will move them (and clarify some things) when LMW-230 is merged.

Let me know if you need anything else :)

**Comment by ngaskill** [comment]
@nhpatt Thanks, looks great! I just did some light edits on the text.

**Comment by ngaskill** [comment]
:+1:

**Pull request merged**
