### PR TITLE
New get user screenlet

### PR DESCRIPTION
**Pull request by mounirovic**
**Case :**
_Given_
When user on screenlet

_When_
User enters a text value which can be an userId, a screenName or an email address

_Then_
Show user informations

**Note :**
getUserBy attribute can take one of three values : userId, screenName or emailAddress. If nothing mentioned, emailAddress is by default.

### CODE REVIEW

**Comment by nhpatt** [comment]
don't worry about the tests, I'll review the pull and fix them

Thank you so much! :D

**Comment by mounirovic** [comment]
Thank you , you too.

**Comment by mounirovic** [comment]
With two last commits, we display users data in a ListView. 

Note : For me, there is no WIP on this pull request. Please, tell me if you have any comments. Thank you !

**Comment by nhpatt** [comment]
Thanks for the contribution :)

Merged [here](https://github.com/liferay/liferay-screens/pull/381#pullrequestreview-16339815)

Thank you so much :D

**Comment by nhpatt** [comment]
I've updated the branch with your author tag and a small README: https://github.com/liferay/liferay-screens/pull/382/files

Thank you again for the contribution! :D

**Comment by victorg1991** [comment]
thank you @mounirovic ! good job!

**Comment by mounirovic** [comment]
It was a pleasure to contribute ! Thank you so much for your merge !

**Pull request closed without merging**
