### PR TITLE
LMW-234 Support upload new picture in UserPortraitScreenlet

### PR DESCRIPTION
**Pull request by jmnavarro**

### CODE REVIEW

**Comment by jmnavarro** [comment]
cc @nhpatt ready to be reviewed again

**Comment by jmnavarro** [comment]
Hey @ngaskill! I changed the doc. Could you review please?

BTW: I read you're using "compulsory" to refer to "required" attributes. Do you think it's a common world? I never use that and rarely see in tech world, but I usually see "mandatory" or "required". What do you think?

Thanks!

**Comment by ngaskill** [comment]
@jmnavarro I edited the changes. Note that the iOS UserPortraitScreenlet reference doc has the load(userId) duplicated in the Methods table. Is this a mistake, or does the method have additional parameters that were left out on accident?

I also changed "Compulsory" to "Required" in the Android screenlet reference docs. I agree that Required/Mandatory are much more common.

**Comment by jmnavarro** [comment]
@ngaskill RE: the load methods, this screenlet provides several versions, so what I did was just document all of them

**Comment by ngaskill** [comment]
@jmnavarro I see the additional load methods, but the load(userId) method is listed twice.

**Comment by nhpatt** [comment]
:+1:

**Pull request merged**
