### PR TITLE
LMW-230 Changes in Westeros App

### PR DESCRIPTION
**Pull request by nhpatt**

### CODE REVIEW

**Comment by jmnavarro** [comment]
When I run the tests, I get 66 fails, all of them with exception `java.lang.RuntimeException: No 'constants' field in @Config annotation!`

**Comment by nhpatt** [comment]
I'll modify the gradle test runner. Now it's flaky (before it only worked through Android Studio and not through Gradle).

**Comment by jmnavarro** [comment]
:+1:

**Comment by nhpatt** [comment]
Hope that all issues solved:
* Processed the result of updating the portrait image to recover the user information
* Created an AssetClassNameIdEE to store the EE constants
* Changed the tests configuration (there is a bug in MAC :()

And finished the pull request moving the material folder outside the main package (as we said)

**Pull request merged**
